### ISSUE TITLE
Does not build on Ubuntu 22.04 (GCC 11.2.0)

### ISSUE THREAD

**Issue by calmsacibis995** [commanderx16/x16-emulator#417]
I am attempting to build the X16 emulator, only to get this:

/usr/bin/ld: build/extern/src/ym2151.o:/home/zerocool32/x16-emulator/src/extern/src/ym2151.c:86: multiple definition of `test'; build/main.o:/home/zerocool32/x16-emulator/src/main.c:130: first defined here
collect2: error: ld returned 1 exit status

Has anyone else got this error?

**Comment by irmen** [comment]
duplicate of #412

**Comment by danboid** [comment]
Mor specifcally, remove the line

```
bool test = true;
```

**Comment by irmen** [comment]
the above linked PR does exactly that

**Comment by calmsacibis995** [comment]
OK, the problem has been solved, it now also builds under Debian Testing with GCC 12.2.
